Flownative:
  Neos:
    CustomDocumentUriRouting:
      mixinNodeTypeName: 'Flownative.Neos.CustomDocumentUriRouting:UriPathMixin'
      uriPathPropertyName: 'uriPath'
      matchExcludePatterns:
        - '_Resources'
